cookie:
  expiry_days: 1
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    acfischer:
      email: acfischer@hcpa.edu.br
      logged_in: false
      name: "Andr\xE9ia Caroline Fischer da Silveira Fischer"
      password: $2b$12$k5M8bMQR07/BkQom28MNt.N4uuWcmEGxn8DO5nDJRoGBqGfir8gJi
    fernanda:
      email: frdoliveira@hcpa.edu.br
      logged_in: false
      name: Fernanda Ramos de Oliveira
      password: $2b$12$B1I39cz4iCDXHAVu9vhUEOOZE64c6QuESGag8QHt5NcGxOZnql1v.
    grgarcia:
      email: grgarcia@hcpa.edu.br
      logged_in: false
      name: Guilherme
      password: $2b$12$eTJTdZmPo6eKsbvSob3TEuNKIlB/IUgCCtPrpFyo5YCma5N5qHI9e
    jbsalazar:
      email: jbsalazar@hcpa.edu.br
      logged_in: false
      name: Josiane Bueno Salazar
      password: $2b$12$NFRUUtK7CIACv3CAZiWikObf4dLsjsSW1VajF1dQo6gP8W.LPATEC
    jrdnascimento:
      email: jrdnascimento@hcpa.edu.br
      logged_in: false
      name: "Joct\xE3 Ropke do Nascimento"
      password: $2b$12$k87v1b/7JBsS5lSWHlzvyeFAV7hDFXr3sio40TqwYXu3ZEelyJ5C.
    ledsouza:
      email: ledsouza@hcpa.edu.br
      logged_in: true
      name: Leandro da Silva de Souza
      password: $2b$12$n0pLYqh/6rbGnP8EOZwUu.wimJuW0MOlZYjOLasUu2IKXX2XjJlOG
    rhann:
      email: rhann@hcpa.edu.br
      logged_in: false
      name: Rodrigo
      password: $2b$12$lntybVv/PY3UObw7HhYdLOXHIdxt95buq7Wizi2XfojJYr.UrIhfi
preauthorized:
  emails:
  - jbsalazar@hcpa.edu.br
