cookie:
  expiry_days: 1
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    ledsouza:
      email: ledsouza@hcpa.edu.br
      logged_in: true
      name: Leandro Souza
      password: $2b$12$n0pLYqh/6rbGnP8EOZwUu.wimJuW0MOlZYjOLasUu2IKXX2XjJlOG
    teste:
      email: teste@hcpa.edu.br
      logged_in: false
      name: teste2
      password: $2b$12$QdAH3.8y5UQhbyVKe0Lqp.pwy45GT7WskHgIZIMNQMVgbLD/GBwIO
preauthorized:
  emails:
  - jbsalazar@hcpa.edu.br
