cookie:
  expiry_days: 1
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    ledsouza:
      email: ledsouza@hcpa.edu.br
      logged_in: true
      name: Leandro Souza
      password: $2b$12$n0pLYqh/6rbGnP8EOZwUu.wimJuW0MOlZYjOLasUu2IKXX2XjJlOG
    teste:
      email: teste2@hcpa.edu.br
      logged_in: false
      name: teste2
      password: $2b$12$OkJqdolc12sElUZyhAOrLOgXJuQfEFVEfUVx.ldc.atjzTXWHCjS.
preauthorized:
  emails:
  - jbsalazar@hcpa.edu.br
  - leandro.souza.159@gmail.com
