cookie:
  expiry_days: 1
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    ledsouza:
      email: ledsouza@hcpa.edu.br
      logged_in: true
      name: Leandro Souza
      password: $2b$12$zw27DFO2YH4JX1D355Nw9.KFlx9lbnkuWqhj2x2EgtOLwJ4njsaay
preauthorized:
  emails:
  - jbsalazar@hcpa.edu.br
  - leandro.souza.159@gmail.com
