cookie:
  expiry_days: 1
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    ledsouza:
      email: ledsouza@hcpa.edu.br
      logged_in: true
      name: Leandro Souza
      password: $2b$12$mPn.9Whufep5L7dZGUTCP.6y2lvKL.pYuJ3kX7bxspCriDBOSU/1K
preauthorized:
  emails:
  - jbsalazar@hcpa.edu.br
  - leandro.souza.159@gmail.com
